-- THIS MIGRATION IS TO SYNC ALL SUCH SEQUENCE WHICH ARE TO BE RECALIBERATED
SET FEEDBACK OFF ;
SET SERVEROUTPUT OFF ;
SPOOL SYNC_SEQUENCES.LOG

CREATE OR REPLACE PROCEDURE SYNC_SEQ (SEQNAME IN VARCHAR2, TABLENAME IN VARCHAR2)
IS
	SEQ_VAL     	PLS_INTEGER;
	ID_VAL          PLS_INTEGER;
	DIFF            PLS_INTEGER;
	INC             PLS_INTEGER;
BEGIN
    EXECUTE IMMEDIATE 'SELECT '|| SEQNAME ||'.NEXTVAL FROM DUAL' INTO SEQ_VAL;
    EXECUTE IMMEDIATE 'SELECT MAX(ID) FROM '||TABLENAME||''      INTO ID_VAL;
    SELECT INCREMENT_BY INTO INC FROM USER_SEQUENCES WHERE SEQUENCE_NAME = UPPER(SEQNAME) ;
    DIFF := ID_VAL - SEQ_VAL;
    IF DIFF > 0
    THEN
        EXECUTE IMMEDIATE 'ALTER SEQUENCE  '|| SEQNAME ||' INCREMENT BY ' ||TO_CHAR(DIFF);
        EXECUTE IMMEDIATE 'SELECT '|| SEQNAME ||'.NEXTVAL FROM DUAL' INTO SEQ_VAL;
        EXECUTE IMMEDIATE 'ALTER SEQUENCE  '|| SEQNAME ||' INCREMENT BY ' || TO_CHAR(INC);
        EXECUTE IMMEDIATE 'SELECT '|| SEQNAME ||'.NEXTVAL FROM DUAL' INTO SEQ_VAL;
    END IF;
END;
/
-- USAGE EXEC SYNC_SEQ('SEQUENCE_NAME','TABLE_NAME');

COMMIT ;
SPOOL OFF ;